# Generated by Django 2.2.6 on 2019-12-20 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_auto_20191220_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='is_subscribed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
