# Generated by Django 2.2.6 on 2019-12-20 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0003_newsletter_is_subscribed'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='is_sent',
            field=models.BooleanField(default=False),
        ),
    ]
