# Generated by Django 2.2.6 on 2019-12-20 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0004_newsletter_is_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='expired',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
