# Generated by Django 2.2.6 on 2019-12-20 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0005_auto_20191220_1032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='expired',
        ),
        migrations.RemoveField(
            model_name='newsletter',
            name='is_sent',
        ),
        migrations.RemoveField(
            model_name='newsletter',
            name='token',
        ),
        migrations.CreateModel(
            name='Activation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, max_length=100, null=True)),
                ('expired', models.DateTimeField(blank=True, null=True)),
                ('is_sent', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('newsletter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='newsletter.NewsLetter')),
            ],
            options={
                'verbose_name': 'Activation',
                'verbose_name_plural': 'Activations',
            },
        ),
    ]
