# Generated by Django 2.2.6 on 2019-12-20 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0006_auto_20191220_1058'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activation',
            options={'ordering': ('-created',), 'verbose_name': 'Activation', 'verbose_name_plural': 'Activations'},
        ),
    ]
