# Generated by Django 2.2.6 on 2019-12-20 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0007_auto_20191220_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activation',
            name='token',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
    ]
