# Generated by Django 2.2.6 on 2019-12-20 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0009_auto_20191220_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activation',
            name='token',
            field=models.CharField(blank=True, editable=False, max_length=250, null=True, unique=True),
        ),
    ]
